### ISSUE TITLE
ERROR Cannot find main class `RealEstatePlugin'

### ISSUE THREAD

**Issue by SrBedrock** [op65n/RealEstate#1]
```
[01:23:05 ERROR]: Could not load 'plugins\RealEstate-1.0.0-Alpha.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Cannot find main class `RealEstatePlugin'
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:81) ~[patched_1.16.4.jar:git-Purpur-952]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:137) ~[patched_1.16.4.jar:git-Purpur-952]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:397) ~[patched_1.16.4.jar:git-Purpur-952]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:305) ~[patched_1.16.4.jar:git-Purpur-952]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:389) ~[patched_1.16.4.jar:git-Purpur-952]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:216) ~[patched_1.16.4.jar:git-Purpur-952]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:937) ~[patched_1.16.4.jar:git-Purpur-952]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[patched_1.16.4.jar:git-Purpur-952]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.ClassNotFoundException: RealEstatePlugin
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:182) ~[patched_1.16.4.jar:git-Purpur-952]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.16.4.jar:git-Purpur-952]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Unknown Source) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:79) ~[patched_1.16.4.jar:git-Purpur-952]
        ... 8 more
```

**Comment by Frcsty** [comment]
Fixed, refactoring messed it up.
